/// A type for results generated by interacting with serial ports.https://doc.rust-lang.org/std/mem/struct.ManuallyDrop.html
pub type Result<T> = serialport::Result<T>;

// Enums, Structs, and Traits from the serialport crate
pub use serialport::{
    // Enums
    ClearBuffer,
    DataBits,
    // Structs
    Error,
    ErrorKind,
    FlowControl,
    Parity,
    // Traits
    SerialPort,

    SerialPortInfo,
    SerialPortSettings,

    StopBits,
};

// Re-export port-enumerating utility function
pub use serialport::available_ports;

#[cfg(unix)]
mod unix;
#[cfg(unix)]
pub use crate::unix::*;

#[cfg(windows)]
mod windows;
#[cfg(windows)]
pub use crate::windows::*;
